# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET https://localhost:7199/todos
###

GET https://localhost:7199/todos/1
###

GET https://localhost:7199
###

POST https://localhost:7199/todos
content-Type: application/json
{
  "Id": 1,
  "Name": "First Todo",
  "DueDate": "2025-12-31",
  "IsCompleted": false
}

###

DELETE https://localhost:7199/todos/1
###

GET https://localhost:7199/tasks/1
###

GET https://localhost:7199/tasks

